### ISSUE TITLE
Tempo screen shows 404 error

### ISSUE THREAD

**Issue by gliptak** [joe-elliott/tempo-springboot-example#4]
Following this setup and clicking Loki button shows Tempo screen 404 errors:

![image](https://user-images.githubusercontent.com/50109/111326863-4ac09d00-8643-11eb-9048-aa4f9b314e09.png)

I don't seem to have failures in the Docker stack logs.

Any pointers on how to debug/correct this?

**Comment by joe-elliott** [comment]
I just noticed and fixed this yesterday I think. There was a mismatch between the tempo and tempo-query images.

[This commit](https://github.com/joe-elliott/tempo-springboot-example/commit/c6ec5246da345490084a2963851a9d6f4a7b002c) should have fixed it. Can you try this?

**Comment by gliptak** [comment]
https://grafana.com/docs/tempo/latest/troubleshooting/unable-to-see-trace/

**Comment by gliptak** [comment]
@joe-elliott could you check this reference https://github.com/joe-elliott/tempo-springboot-example/blob/master/stack.yml#L42 ?

`./etc/tempo-query.yaml` isn't available in the repo

**Comment by gliptak** [comment]
yes, update to matching `tempo` / `tempo-query` versions corrected this, Thanks @joe-elliott
