### ISSUE TITLE
loki 2.2.0 breaks tempo link

### ISSUE THREAD

**Issue by gliptak** [joe-elliott/tempo-springboot-example#6]
![image](https://user-images.githubusercontent.com/50109/111368610-799f3900-866c-11eb-86ab-6027f12298a3.png)

Is there a compatibility matrix between loki and tempo I need to review?

**Comment by joe-elliott** [comment]
Nope. I think I've only seen that when the backend is down.

If you submit a PR to update to Loki 2.2.0 that reproduces this issue I can run it locally and do some debugging.

**Comment by joe-elliott** [comment]
I just ran through the whole demo using your branch and everything worked.  Unsure where that error came from.
